---
title: "LO2"
output: html_notebook
---

# LIBRARY AND DATA
## LOADING AND INSTALLATION
```{r}
#Installation
#install.packages("tidyverse")
#install.packages("gapminder")
```

```{r}
#loading 
library(tidyverse)
library(gapminder)
```

## STORE DATA
```{r}
gm_data <- gapminder
```

# OVERVIEW
## STRUCTURE

```{r}
str(gm_data)
```

```{r}
summary(gm_data)
```

```{r}
gm_1997 <- gm_data %>% filter(year == 1997)

```


# SIZE
##Graph 1
```{r}
ggplot(gm_1997, aes(x = gdpPercap, y = lifeExp))+
  geom_point()+
  labs(title= "Life expectancy depending on GDP 1997 in Africa",
       x = "GDP",
       y = "Life expectancy",
       )
```
##Graph 2
```{r}
ggplot(gm_1997, aes(x = gdpPercap, y = lifeExp))+
  geom_point(size = 4)+
  labs(title= "Life expectancy depending on GDP 1997 in Africa",
       x = "GDP",
       y = "Life expectancy",
       )
```


# SHAPE
##Graph 3
```{r}
ggplot(gm_1997, aes(x = gdpPercap, y = lifeExp))+
  geom_point(shape = 3, size = 2)+
  labs(title= "Life expectancy depending on GDP 1997 in Africa",
       x = "GDP",
       y = "Life expectancy",
       )
```

##Graph 4
```{r}
ggplot(gm_1997, aes(x = gdpPercap, y = lifeExp))+
  geom_point(shape = 18, size = 3)+
  labs(title= "Life expectancy depending on GDP 1997 in Africa",
       x = "GDP",
       y = "Life expectancy",
       )
```

# COLOR VALUE
##Graph 5
```{r}
ggplot(gm_1997, aes(x = gdpPercap, y = lifeExp))+
  geom_point(alpha = 0.3, size = 4)+
  labs(title= "Life expectancy depending on GDP 1997 in Africa",
       x = "GDP",
       y = "Life expectancy",
       )
```

##Graph 6
```{r}
ggplot(gm_1997, aes(x = gdpPercap, y = lifeExp, color = country))+
  geom_point(alpha = 0.3, size = 4, color = "blue")+
  labs(title= "Life expectancy depending on GDP 1997 in Africa",
       x = "GDP",
       y = "Life expectancy",
       )
```


# ORIENTATION
##Graph 7
```{r}
ggplot(gm_1997, aes(x = gdpPercap, y = lifeExp))+
  geom_point(alpha = 0.5, size = 4 )+
  labs(title= "Life expectancy depending on GDP 1997 in Africa",
       x = "GDP",
       y = "Life expectancy"
       )
```

##Graph 8
```{r}
ggplot(gm_1997, aes(x = gdpPercap, y = lifeExp, shape = continent))+
  geom_point(alpha = 0.5, size = 4, color = "red" )+
  labs(title= "Life expectancy depending on GDP 1997 in Africa",
       x = "GDP",
       y = "Life expectancy"
       )
```

#COLOR HUE
##Graph 9

```{r}
ggplot(gm_1997, aes(x = gdpPercap, y = lifeExp))+
  geom_point(alpha = 0.5, size = 4 )+
  labs(title= "Life expectancy depending on GDP 1997 in Africa",
       x = "GDP",
       y = "Life expectancy"
       )
```

##Graph 10
```{r}
ggplot(gm_1997, aes(x = gdpPercap, y = lifeExp))+
  geom_point(alpha = 0.5, size = 4, aes(color = continent) )+
  labs(title= "Life expectancy depending on GDP 1997 in Africa",
       x = "GDP",
       y = "Life expectancy"
       )
```









